# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f7d365a8ba2e6f8880dcafed790c5e8e3a870714b6974d6af5afa390cfc293dc61211cf8604fd36827bd0897097631676db558dff19439cea7b735d3db9ddd

test:
  secret_key_base: 681932011107120086e140faac73c89c3f749d9cc0e6fc9b218bc8bbb8b39ed926a3ce81818764276e01be5463f342a6340b97feea429970a6eac90e1e742b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
